import type { z } from "zod";
import { DefaultFieldType } from "../constants";
import type { components } from "./api-definition";

// declare a brand for the UmbracoFormSchema type to ensure that the provided schema is a valid schema generated by the umbracoFormToZod function
declare const __brand: unique symbol;
type Brand<B> = { [__brand]: B };
export type Branded<T, B> = T & Brand<B>;

export type UmbracoFormSchema = Branded<
  z.ZodEffects<z.ZodObject<Record<string, z.ZodTypeAny>>>,
  "UmbracoFormSchema"
>;

export interface DefaultFieldTypeNameMap {
  [DefaultFieldType.Checkbox]: "Checkbox";
  [DefaultFieldType.DataConsent]: "Data consent";
  [DefaultFieldType.Date]: "Date";
  [DefaultFieldType.DropdownList]: "Dropdown";
  [DefaultFieldType.FileUpload]: "File upload";
  [DefaultFieldType.LongAnswer]: "Long answer";
  [DefaultFieldType.HiddenField]: "Hidden field";
  [DefaultFieldType.ShortAnswer]: "Short answer";
  [DefaultFieldType.MultipleChoice]: "Multiple choice";
  [DefaultFieldType.Recaptcha2]: "Recaptcha2";
  [DefaultFieldType.RecaptchaV3WithScore]: "Recaptcha v3 with score";
  [DefaultFieldType.Password]: "Password";
  [DefaultFieldType.RichText]: "Rich text";
  [DefaultFieldType.SingleChoice]: "Single choice";
  [DefaultFieldType.TitleAndDescription]: "Title and description";
}

/** Field type settings
 * @see https://docs.umbraco.com/umbraco-forms/developer/configuration/type-details#field-types */
export interface FieldSettings {
  [DefaultFieldType.ShortAnswer]: {
    defaultValue: string;
    placeholder: string;
    showLabel: string;
    maximumLength: string;
    fieldType: string;
    autocompleteAttribute: string;
  };
  [DefaultFieldType.LongAnswer]: {
    defaultValue: string;
    placeholder: string;
    showLabel: string;
    autocompleteAttribute: string;
    numberOfRows: string;
    maximumLength: string;
  };
  [DefaultFieldType.HiddenField]: {
    defaultValue: string;
  };
  [DefaultFieldType.Checkbox]: {
    caption: string;
    defaultValue: string;
    showLabel: string;
  };
  [DefaultFieldType.DropdownList]: {
    defaultValue: string;
    allowMultipleSelections: string;
    showLabel: string;
    autocompleteAttribute: string;
    selectPrompt: string;
  };
  [DefaultFieldType.MultipleChoice]: {
    defaultValue: string;
    showLabel: string;
    preValues: Array<unknown>;
  };
  [DefaultFieldType.DataConsent]: {
    acceptCopy: string;
    showLabel: string;
  };
  [DefaultFieldType.FileUpload]: {
    selectFilesListHeading: string;
  };
  [DefaultFieldType.Recaptcha2]: {
    theme: string;
    size: string;
    errorMessage: string;
  };
  [DefaultFieldType.RecaptchaV3WithScore]: {
    scoreThreshold: string;
    errorMessage: string;
    saveScore: string;
  };
  [DefaultFieldType.Date]: {
    placeholder: string;
  };
  [DefaultFieldType.Password]: {
    placeholder: string;
  };
  [DefaultFieldType.RichText]: {
    showLabel: string;
    html: string;
  };
  [DefaultFieldType.SingleChoice]: {
    defaultValue: string;
    showLabel: string;
  };
  [DefaultFieldType.TitleAndDescription]: {
    captionTag: string;
    caption: string;
    bodyText: string;
    showLabel: string;
  };
}

/** Form definition
 * @see https://docs.umbraco.com/umbraco-forms/editor/creating-a-form/form-settings */
export interface FormDto
  extends Omit<components["schemas"]["FormDto"], "pages"> {
  pages?: FormPageDto[];
}

/** Form page
 * @see https://docs.umbraco.com/umbraco-forms/editor/creating-a-form#form-pages */
export interface FormPageDto
  extends Omit<components["schemas"]["FormPageDto"], "fieldsets"> {
  fieldsets?: FormFieldsetDto[];
}

/** Form groups
 * @see https://docs.umbraco.com/umbraco-forms/editor/creating-a-form#form-groups */
export interface FormFieldsetDto
  extends Omit<components["schemas"]["FormFieldsetDto"], "columns"> {
  columns?: FormFieldsetColumnDto[];
}

/** Form fieldset column
 * @see https://docs.umbraco.com/umbraco-forms/editor/creating-a-form#form-columns */
export interface FormFieldsetColumnDto
  extends Omit<components["schemas"]["FormFieldsetColumnDto"], "fields"> {
  fields?: FormFieldDto[];
}

/** Form field type
 * @see https://docs.umbraco.com/umbraco-forms/developer/configuration/type-details#field-types */
export interface FormFieldTypeDto
  extends Omit<components["schemas"]["FormFieldTypeDto"], "name"> {
  name: DefaultFieldTypeNameMap[DefaultFieldType];
  id: DefaultFieldType;
}

/** Form field
 * @see https://docs.umbraco.com/umbraco-forms/developer/configuration/type-details#field-types */
export interface FormFieldDto
  extends Omit<components["schemas"]["FormFieldDto"], "type" | "settings"> {
  type: FormFieldTypeDto | { id: string; name: string };
  settings: FieldSettings[DefaultFieldType] | Record<string, string>;
}

/** Form condition
 * @see https://docs.umbraco.com/umbraco-forms/editor/creating-a-form/conditional-logic */
export type FormConditionDto = components["schemas"]["FormConditionDto"];

/** Form condition rule
 * @see https://docs.umbraco.com/umbraco-forms/editor/creating-a-form/conditional-logic */
export type FormConditionRuleDto =
  components["schemas"]["FormConditionRuleDto"];

/** Field condition action type
 * @see https://docs.umbraco.com/umbraco-forms/editor/creating-a-form/conditional-logic#action-and-logic-types */
export type FieldConditionActionType =
  components["schemas"]["FieldConditionActionType"];

/** Field condition logic type
 * @see https://docs.umbraco.com/umbraco-forms/editor/creating-a-form/conditional-logic#action-and-logic-types */
export type FieldConditionLogicType =
  components["schemas"]["FieldConditionLogicType"];

/** Field condition rule operator
 * @see https://docs.umbraco.com/umbraco-forms/editor/creating-a-form/conditional-logic#adding-a-new-condition */
export type FieldConditionRuleOperator =
  components["schemas"]["FieldConditionRuleOperator"];

/** Data transfer object with conditions, includes pages, fieldsets and fields
 * @see https://docs.umbraco.com/umbraco-forms/editor/creating-a-form/conditional-logic */
export type DtoWithCondition = FormPageDto | FormFieldsetDto | FormFieldDto;

/** Configuration for the UmbracoForm component instance */
export type UmbracoFormConfig = {
  /** Custom schema for form validation; defaults to the umbracoFormToZod implementation */
  schema: UmbracoFormSchema;
  /** Optional custom function to map form fields to Zod types, useful for handling custom field types */
  mapCustomFieldToZodType?: MapFormFieldToZodFn;
} & (
  | {
      /** Flag indicating if client-side validation should be performed; defaults to `false` */
      shouldValidate: true;
      /** Flag indicating if native browser validation should be used alongside client-side validation; defaults to `false` */
      shouldUseNativeValidation?: false;
      /** Flag indicating if the form should be validated on change, blur, or submit; defaults to `onSubmit` */
      validateMode?: "onBlur" | "onSubmit" | "onChange" | "all";
      /** Re-validate the form on change, blur, or submit; defaults to `onBlur` */
      reValidateMode?: "onChange" | "onBlur" | "onSubmit";
    }
  | {
      shouldValidate: true;
      shouldUseNativeValidation: true;
      validateMode?: never;
      reValidateMode?: never;
    }
  | {
      shouldValidate?: false;
      shouldUseNativeValidation?: never;
      validateMode?: never;
      reValidateMode?: never;
    }
);

export type MapFormFieldToZodFn = (field?: FormFieldDto) => z.ZodTypeAny;
